version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - ${POSTGRESQL_PORT}
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
  keycloak:
    platform: linux/amd64
    image:
      quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: keycloak
    ports:
      - ${KEYCLOAK_PORT}
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    depends_on:
      - postgres
    command:
      - start-dev
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - ${ZOOKEEPER_PORT}
  kafka:
    platform: linux/arm64
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - ${KAFKA_PORT}
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_INNER_PORT}